# Generated by Django 3.2.9 on 2021-11-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 17, 15, 55, 105470)),
        ),
    ]
