# Generated by Django 3.2.9 on 2021-11-06 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211106_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 17, 36, 29, 783047)),
        ),
    ]
