# Generated by Django 3.2.9 on 2021-11-07 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211107_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 16, 10, 1, 7042)),
        ),
    ]
